remote_theme: pages-themes/cayman@v0.2.0

plugins:
  - jekyll-remote-theme

title: "Trip Times and Trends"
description: >
  A Data-Driven Analysis and Prediction of Taxi Trip Durations <br>
  Drake Graham <br>
  dgraham7362@gmail.com

show_downloads: false
google_analytics: UA-XXXXXXX-X
